# Github default settings that can be changed.
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
#theme: minima
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# Github default settings that can't be changed. (Github will override them.)
# Can set them to whatever we want for local testing.
lsi: false
safe: true
# Just let source get set by default.
#source: [your repo's top level directory]
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Other settings (Github doesn't mess with these).

# Kramdown options: https://kramdown.gettalong.org/options.html
kramdown:
  #auto_ids: false # Don't turn headings into anchors.

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: 'assets'
    values:
      layout: null

sass:
  sass_dir: _sass

exclude: [scripts]

