github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# Can't change these settings (Github overrides them).
# Can set them to whatever we want for local testing.
lsi: false
safe: true
# Just let source get set by default.
#source: [your repo's top level directory]
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

