#!/bin/sh

THUMB_HEIGHT=128
LARGE_HEIGHT=512

for f in $(ls *.jpg | fgrep -v .thumb. | fgrep -v .large.); do
  LARGE=$(basename "$f" .jpg).thumb.jpg
  THUMB=$(basename "$f" .jpg).large.jpg
  [ ! -f "$LARGE" ] && convert "$f" -resize x$LARGE_HEIGHT "$LARGE"
  [ ! -f "$THUMB" ] && convert "$f" -resize x$THUMB_HEIGHT "$THUMB"
  echo rm $f
done

